### PR TITLE
Add front-end testing to style guide

### PR DESCRIPTION
**Pull request by VictorSpulveda**
[Atomic design testing](https://github.com/GeekHunter-Brasil/hello-world/tree/feat--front-end-tests/frontend-styleguide#pushpin-atomic-design-testing)

### CODE REVIEW

**Review by pedro-lb — COMMENTED** [review]
Should we merge this with https://github.com/GeekHunter-Brasil/hello-world/pull/30?

@joaophellip @paulohenriquepm

**Comment by joaophellip** [comment]
> Should we merge this with #30?
> 
> @joaophellip @paulohenriquepm

Yeah! Reserver a slot to finish PR 30 this afterrnoon.

@pedro-lb what if we merge this in master, still in same release, and then I add these to the Testing SG (PR 30) as a new release?

**Comment by VictorSpulveda** [comment]
> > Should we merge this with #30?
> > @joaophellip @paulohenriquepm
> 
> Yeah! Reserver a slot to finish PR 30 this afterrnoon.
> 
> @pedro-lb what if we merge this in master, still in same release, and then I add these to the Testing SG (PR 30) as a new release?

I had planned to leave this in draft and adapt this code there for the Testing SG after the merge of PR 30

**Comment by joaophellip** [comment]
> > > Should we merge this with #30?
> > > @joaophellip @paulohenriquepm
> > 
> > 
> > Yeah! Reserver a slot to finish PR 30 this afterrnoon.
> > @pedro-lb what if we merge this in master, still in same release, and then I add these to the Testing SG (PR 30) as a new release?
> 
> I had planned to leave this in draft for now and then adapt this code there for the Testing SG after the merge of PR 30, so we can review this PR separately

Works for me too!

**Comment by paulohenriquepm** [comment]
I will close this PR because the content was merged with this [PR](https://github.com/GeekHunter-Brasil/hello-world/pull/30)

**Pull request closed without merging**
